// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "gozu/domain"

	mock "github.com/stretchr/testify/mock"
)

// StockRepo is an autogenerated mock type for the StockRepo type
type StockRepo struct {
	mock.Mock
}

// GetStockSummary provides a mock function with given fields: stockCode
func (_m *StockRepo) GetStockSummary(stockCode string) (*domain.StockSummary, error) {
	ret := _m.Called(stockCode)

	var r0 *domain.StockSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.StockSummary, error)); ok {
		return rf(stockCode)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.StockSummary); ok {
		r0 = rf(stockCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StockSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(stockCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteStockSummary provides a mock function with given fields: summary
func (_m *StockRepo) WriteStockSummary(summary *domain.StockSummary) error {
	ret := _m.Called(summary)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.StockSummary) error); ok {
		r0 = rf(summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewStockRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewStockRepo creates a new instance of StockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStockRepo(t mockConstructorTestingTNewStockRepo) *StockRepo {
	mock := &StockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
